### ISSUE TITLE
Accessibility: Icons need labels for screen reader users

### ISSUE THREAD

**Issue by glombek** [PerplexDigital/Perplex.ContentBlocks#11]
Buttons requiring labels:

- Expand/collapse toggle chevron
- Layout carousel
- Settings cog

**Comment by PerplexDaniel** [comment]
Feel free to add (invisible) labels for screen readers to this, as always make sure it doesn't break layout in the normal views.

**Comment by PerplexDaniel** [comment]
Closed due to 4 weeks of inactivity.
Feel free to reopen with new input.

**Comment by glombek** [comment]
This issue should not be closed due to inactivity - these will take time to fix but remain severe accessibility issues.
