### ISSUE TITLE
Create a Perplex.ContentBlocks.Core Nuget package

### ISSUE THREAD

**Issue by chrisdent14** [PerplexDigital/Perplex.ContentBlocks#14]
I would be handy to have the core classes separated into a different Nuget package so that the Content Block Definitions can be stored in a separate project if required, without the need to include the whole package (including App_Plugins folder). 

The workaround for this I have at the moment (not a good one) is to include the reference to Perplex.ContentBlocks from the packages folder into my separate project manually which will obviously be out of date when the package is updated.

I hope this makes sense and happy to share more if you need more information.

**Comment by PerplexDaniel** [comment]
I can see why this can be useful indeed. We are a bit busy right now so not much time to work on this  package, but I will try to have a look at this next week or so and will update this issue.

**Comment by chrisdent14** [comment]
@PerplexDaniel Thanks for the reply Daniel. No major rush so I'll just keep watch on this for now then.
Thanks

**Comment by PerplexDaniel** [comment]
@chrisdent14 `Perplex.ContentBlocks.Core` package [is available on NuGet now](https://www.nuget.org/packages/Perplex.ContentBlocks.Core).
