### ISSUE TITLE
Accessibility: Smart preview hijacks keyboard navigation

### ISSUE THREAD

**Issue by glombek** [PerplexDigital/Perplex.ContentBlocks#16]
Smart preview hijacks keyboard navigation and the user ends up navigating the complete page. This could be confusing for screen reader users (although it is announced as a "frame"), but is frustrating for keyboard navigation as there doesn't seem to be a way to skip to the buttons below the preview.

I'm not entirely sure how it's best to solve this problem.

Some suggestions:
- prevent focusing the preview and hide from screen readers
- add a "Skip preview" link (like a skip to main content link)
- add a button to manually focus the preview, skip unless button is clicked

**Comment by PerplexDaniel** [comment]
Closed due to 4 weeks of inactivity.
Feel free to reopen with new input.

**Comment by glombek** [comment]
This issue should not be closed due to inactivity - these will take time to fix but remain severe accessibility issues.
