### ISSUE TITLE
missing db

### ISSUE THREAD

**Issue by ismailmayat** [PerplexDigital/Perplex.ContentBlocks#2]
would it be possible to get copy of demo site db with login?

**Comment by PerplexDaniel** [comment]
No, but there is no real value in it. Mostly just the Umbraco StarterKit, which you can install yourself very easily:
Clear `"Umbraco.Core.ConfigurationStatus`" and the `<connectionStrings>` in `Web.config`, then run the site you will be prompted to install Umbraco. You can just press "Next/Continue" a few times and you are set.

The DemoSite will create an example header/example block through code (like in README) so if you then just add the datatype to some doctype it should work. Views are already present there as well.
