### ISSUE TITLE
Add request header for preview request

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#21]
In the preview api controller I can see the umbraco preview badge is removed.
I'm using the Our.Umbraco.EditLink package, which displays an Edit button for logged in users.
I'd like to hide this button for the preview, but am unable to identify the request.

A possible fix is to add a request header (e.q. `X-Perplex-ContentBlocks` or something more generic like `X-Umb-Preview`) which I can check before adding the Edit button,

**Comment by PerplexDaniel** [comment]
You can inject the [`IPreviewModeProvider`](https://github.com/PerplexDigital/Perplex.ContentBlocks/blob/master/src/Perplex.ContentBlocks/Preview/IPreviewModeProvider.cs) to check if the current request is in preview mode, that should work.

**Comment by stefankip** [comment]
You're absolutely right, I wasn't aware of it's existence! Thanks :-)
