### ISSUE TITLE
Question: possible to define multiple content block editors?

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#23]
Quick question; is it possible to have multiple ContentBlock editors with their own configuration? For example in a multi-tenant set-up?
One way I can think of is to have different header and content categories for each editor, is this the way to go?

**Comment by PerplexDaniel** [comment]
It is currently not possible to define separate category names for different block editors.
There is exactly 1 set of categories that is used by all editors you create.

However, you can limit content blocks themselves to either a culture or a document type (see [here](https://github.com/PerplexDigital/Perplex.ContentBlocks#content-block-definition), look for `LimitToDocumentTypes` and `LimitToCultures`).
That way it is possible to offer different sets of blocks to different tenants, assuming each tenant has their own culture or set of doctypes.

**Comment by stefankip** [comment]
Check, I think the `LimitToDocumentTypes` is suffice in this situation :-)
