### ISSUE TITLE
Expose additional umbraco properties inside view

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#25]
I am looking for a way to get a hold of the umbraco content tree so I can traverse and get data from other content pages.
Also I am trying to get data from the current page (like an introduction block which uses title/intro/picture data from current page), but I can't access it inside the view.

I know I'm able to use a Custom View Model and I will, but I can see why it might be handy to be able to access `CurrentPage`, `UmbracoHelper` and `UmbracoContext` from the view.

**Comment by PerplexDaniel** [comment]
If you simply replace 

`@model IContentBlockViewModel<>` 

with 

`@inherits UmbracoViewPage<IContentBlockViewModel<...>>` 

in your .cshtml it will give you access to stuff like `Umbraco.AssignedContentItem` and all the other good stuff you want.

**Comment by stefankip** [comment]
Ah great, might be a nice addition for the documentation? :-)
