### ISSUE TITLE
Sugestion: ability to set max block use per page

### ISSUE THREAD

**Issue by FransdeJong** [PerplexDigital/Perplex.ContentBlocks#27]
It would be great to be able to set a maxusage per page on a contentblock.
It could be a property on the ContentBlockDefinition and than a greyed out version of the block in the overview or something?

**Comment by PerplexDaniel** [comment]
This is to prevent editors from adding the same block a lot of times on a page? I am a bit hesitant to include all sorts of properties for fairly niche use cases in the backoffice on `IContentBlockDefinition`. Not to mention changing that interface would technically be a breaking change as well, although I don't think many people made their own implementation of it.

I'm thinking we can probably add some JavaScript events which can be used to add this kind of logic through your own code. That is, some events like `addBlock` / `openBlockPicker`, etc, which will allow you to just add any custom JS you want in the backoffice. I feel that's probably the better approach for stuff like this. We would still have to make it possible to disable a block in the picker somehow but that can be arranged.

**Comment by stefankip** [comment]
I just don't really understand the usecase; why would you limit the functionality like this for the content editor?

**Comment by FransdeJong** [comment]
Thanks for the answers

First the use case:
I use the blockbuilder on a structuredcontent page, for example product overview.
On the page the editor can pick a header and than content from a selection of contentblocks.

One of the blocks is the actual products. This contains some settings and renders a Vue component that shows the products in the front end.
I only want the editor to pick this block once.

If this use case is a accepted use case than the IContentBlockDefinition looks like the best place for this setting.
All other options feel like a hack?

If the use case is weird than I have to at a different way to solve this indeed.

**Comment by PerplexDaniel** [comment]
I'm sorry I don't think this really warrants a dedicated property on the Content Block definition. This is primarly some UX thing which I hope we can solve in some other way in the future. 

In your specific case I think the client will hopefully realize they should only place 1 product overview on the page without you forcing that in the UI. Although if you make it possible for them to customize the products to show in that block it's not unreasonable to put that block multiple times on the page, showing related products in a couple of blocks. 

Anyway, closing this now but might refer to this later if we have some ideas about how to support some custom UX logic.

If any future reader also wants this functionality feel free to reopen and/or comment.
