### ISSUE TITLE
Bug: re-ordering a block with RTE kills the RTE

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#28]
When you have a content block expanded with a RTE property inside and re-order the content block, the content in the RTE disappears.
Might be a Nested Content issue btw?

**Comment by PerplexDaniel** [comment]
Hmm interesting, willl check it out soon. We collapse all blocks when reordering but that shouldn't do too much to the editors inside. Perhaps if content is hidden using an `ng-if` rather than an `ng-show` this messes up the RTE for example. We'll see.

**Comment by PerplexDaniel** [comment]
So I had a quick look and I can reproduce this.

Nothing related to `ng-if` or `ng-show`, but the RTE `<iframe>` will just be completely empty after having reordered it. Not reordering at all is fine (so enable reorder mode then immediately disable does not kill it). So seemingly rendering the `<perplex-content-block>` component again when its position is changed messes up the RTE inside for some reason.

I look at NestedContent, it seems they completely reload editors after reordering. So I'll do something similar now. When enabling Reorder the editor will be unloaded and when reordering is finished it'll be restored. Seems to work fine.

This should be part of a next release soon. Below you can see it works now:
![contentblocks-rte](https://user-images.githubusercontent.com/24297947/89645561-58968e80-d8ba-11ea-806e-849607d44f0f.gif)

**Comment by stefankip** [comment]
Nice work mate! 💯

**Comment by PerplexDaniel** [comment]
@stefankip Fix is now available to test in `1.5.2-rc.1` on NuGet (prerelease). Make sure to clear any old JS cache. If it does not work for you, let me know.

**Comment by stefankip** [comment]
Yeah works for me :-)
