### ISSUE TITLE
How we use Grid option inside and render value using default @Html.GetGridHtml(Model.Content, "columns")

### ISSUE THREAD

**Issue by pankajinfo3** [PerplexDigital/Perplex.ContentBlocks#29]
How we use Grid option inside and render value using default @Html.GetGridHtml(Model.Content, "columns")

**Comment by PerplexDaniel** [comment]
Are you using a doctype with a Grid property as a ContentBlock? I imagine that should work as usual. In your code example, is `Model` an `IContentBlockViewModel<T>`, where `T` is your doctype? What is the output of `@Html.GetGridHtml()` in your example?

**Comment by pankajinfo3** [comment]
cannot convert from 'Perplex.ContentBlocks.Rendering.IContentBlockViewModel' to 'Umbraco.Core.Models.PublishedContent.IPublishedProperty'

@Html.GetGridHtml(Model, "columnsbuilder")

I am using this way code

**Comment by pankajinfo3** [comment]
I do this code GridValue grid = JsonConvert.DeserializeObject<GridValue>(Model.Content.Value("columnsbuilder").ToString()); to get Grid

**Comment by PerplexDaniel** [comment]
`@Html.GetGridHtml` should be called on `IPublishedContent` or `IPublishedProperty`, so you should call with __Model.Content__, right? `Model` is indeed the `IContentBlockViewModel` so that won't work.

What's the output of `@Html.GetGridHtml(Model.Content, "columnsbuilder")`?

**Comment by PerplexDaniel** [comment]
> I do this code GridValue grid = JsonConvert.DeserializeObject(Model.Content.Value("columnsbuilder").ToString()); to get Grid

Do you want the HTML or the JSON? This code you give will just give you the JSON right? Regardless, anything you do should work the same as on a "normal" Umbraco doctype, as you should be getting the same ModelsBuilder object.

**Comment by pankajinfo3** [comment]
I need HTML

**Comment by pankajinfo3** [comment]
![image](https://user-images.githubusercontent.com/38730738/89500978-36304280-d7e0-11ea-8291-6925d70329b9.png)

**Comment by PerplexDaniel** [comment]
Ah I see, it does not work on `IPublishedElement`, that's interesting.

Anyway, try this to use the overload with an `IPublishedProperty`:

`@Html.GetGridHtml(Model.Content.GetProperty("columnsbuilder"))`

**Comment by pankajinfo3** [comment]
wooowww nice it's work :) thanks

**Comment by pankajinfo3** [comment]
also how i add language that manage by Dictionary created control

**Comment by PerplexDaniel** [comment]
> also how i add language that manage by Dictionary created control

Not sure what you mean by this, but perhaps you can create _a new issue_ for this one and provide some example code. 
I'll close this one now as it's resolved.

**Comment by pankajinfo3** [comment]
Thanks
