### ISSUE TITLE
Don't display layout selector if there's only 1

### ISSUE THREAD

**Issue by skartknet** [PerplexDigital/Perplex.ContentBlocks#3]
Great package guys! Just a little thing. It would be good to don't get the Pick Layout button if there's only 1 layout available.

**Comment by PerplexDaniel** [comment]
Hi @skartknet, understandable suggestion. I know our UX guys generally are not advocates of completely hiding UI elements as it's inconsistent and not always obvious why it's not there. So in that case it would be disabled instead. 

However, the Pick Layout button also provides a better look at the block (it shows the layout preview image which is much larger), so I am not completely sure about disabling this. Yes, you can only pick 1 layout but at the same time you can have a closer look at it.

So I like to keep it like this for now, thanks for your suggestion though I'll keep it in mind and re-open + update when it'll change.

**Comment by skartknet** [comment]
They all sound like good reasons to keep it as is. Thanks.
