### ISSUE TITLE
how we use GetDictionaryValue in component  .cs file ?

### ISSUE THREAD

**Issue by pankajinfo3** [PerplexDigital/Perplex.ContentBlocks#33]
how we use GetDictionaryValue in component  .cs file ?

**Comment by PerplexDaniel** [comment]
How do you normally call `GetDictionaryValue`? I'm not familiar with it. On which class? You have an `IPublishedElement` available in `Model.Content` if that's what you need.

**Comment by pankajinfo3** [comment]
i try to using this in   src/DemoWebsite/Example.cs  file

**Comment by PerplexDaniel** [comment]
Yes but I am not familiar with the `GetDictionaryValue` method. It's a method on what type? That's why I wonder how you normally use this method. Like if the code looks like `X.GetDictionaryValue(Y)`, what are X and Y and what are their types?

**Comment by pankajinfo3** [comment]
ok thanks
