### ISSUE TITLE
Content disappearing since 1.5.2

### ISSUE THREAD

**Issue by PerplexDaniel** [PerplexDigital/Perplex.ContentBlocks#38]
We see some issues in 1.5.2 where content does not show up in the backoffice after publising and refreshing the page. Content still shows up on the front-end and still exists in the database.

This issue is seen internally at Perplex and also reported at [Our Umbraco](https://our.umbraco.com/packages/backoffice-extensions/perplexcontentblocks/feedback-questions/103331-saved-content-issue). 

The data is still present in the database, so the issues is most likely caused by the changes in #34 , probably in the `ToEditor()`.

I cannot reproduce this in the Demo Site included in the solution it seems, which is unfortunate.

**Comment by PerplexDaniel** [comment]
It appears that this issue only occurred in multilingual settings, i.e. where the `culture` of the ContentBlocks property is not `null`. 
There was a bug in the way we were calling some Nested Content method in our `ToEditor()` method which is fixed by the linked PR.
I believe this fixes the issue and will be released after some tests somewhere in the next 24 hours.

**Comment by duanleou90** [comment]
> It appears that this issue only occurred in multilingual settings, i.e. where the `culture` of the ContentBlocks property is not `null`.
> There was a bug in the way we were calling some Nested Content method in our `ToEditor()` method which is fixed by the linked PR.
> I believe this fixes the issue and will be released after some tests somewhere in the next 24 hours.

I'm waiting for fixing. Thanks!

**Comment by PerplexDaniel** [comment]
I have just released `1.5.3` which should fix this issue. If anyone still experiences issues with this when using 1.5.3, please let us know.

**Comment by duanleou90** [comment]
> I have just released `1.5.3` which should fix this issue. If anyone still experiences issues with this when using 1.5.3, please let us know.

I have just tested it on my local instance. And it works well now. Thanks for fixing soon!

**Comment by joepvtl** [comment]
Hey @PerplexDaniel,

We are experiencing this issue. We updated our environment from 1.4.2 to 1.6.0 and now when we save a page that has NC inside of the blocks they dissapear from the backoffice.

We are using Umbraco 8.8.0

-Joep

cc// @vavdb

**Comment by PerplexDaniel** [comment]
Coincidentally someone on Our also [reported this](https://our.umbraco.com/packages/backoffice-extensions/perplexcontentblocks/feedback-questions/103331-saved-content-issue#comment-324530) today. 
Seems indeed again related to the same section of the code, so until we have looked into this and released a fix I recommend to use <= 1.5.1.

**Comment by PerplexDaniel** [comment]
Oh I see. Umbraco recently (I think in 8.7.0) changed the returned values from NestedContent's `ToEditor()` method which we call in ours. It used to be a simple `List<JObject>` (which is what we check for), but has been updated to `IReadOnlyList<NestedContentValues.NestedContentRowValue>` in [this commit](https://github.com/umbraco/Umbraco-CMS/commit/51280845).

So this probably was caused by the Umbraco upgrade rather than the original bug of this issue. 
Regardless, I have added a commit which should fix this. It no longer does an exact type check on `List<JObject>`. Will test it a bit more and should be released soon. 

You can of course clone the PR branch and compile Perplex.ContentBlocks.dll yourself to test if this fixes the issue.

**Comment by PerplexDaniel** [comment]
@joepvtl I just pushed 1.6.1 to NuGet, this should fix the issue.
