### ISSUE TITLE
Remove NC item border in umbraco 8.7

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#42]
Umbraco 8.7 introduced this border around NC items, which looks wonky in Content Blocks:

![image](https://user-images.githubusercontent.com/46313552/94912743-6aef0c00-04a8-11eb-8790-0fd207843ac0.png)

It was added to the class `.umb-nested-content__item`:
```
border: 1px solid #e9e9eb;
border-radius: 3px;
```

I think we can overrule this, right?
```
.perplex-content-blocks .umb-nested-content__item {
    border: none;
}
```

**Comment by PerplexDaniel** [comment]
Agree, this does not look good :) Fixed in 6c306f353ae6a44cca89a295c6a21c72f96ddd18.
