### ISSUE TITLE
Hide previews in splitview

### ISSUE THREAD

**Issue by joepvtl** [PerplexDigital/Perplex.ContentBlocks#47]
Hey Daniël,

![image](https://user-images.githubusercontent.com/42842226/99961525-e1183c80-2d8e-11eb-98a7-3848dd122e89.png)
When using the contentblocks in splitview, it looks kinda weird.
I guess the best thing to do here is to hide them.

**Comment by PerplexDaniel** [comment]
Yeah this should probably be hidden indeed. We also noticed this. I believe we have something scheduled in another project to fix this. Would probably hide the right column but move the buttons to the main column so they can still be used. The block name / layout name width also should be distributed properly... 

Until that fix is released (not sure on ETA) it's easiest to just include some CSS yourself to hide this preview column entirely when inside splitview.

**Comment by bramdoppen** [comment]
Hi @joepvtl, Thanks for creating this issue. 
We fixed this issue and added some more style improvements in branch #49 

When it's merged and relased, you can update the package. In the meantime you can copy some code from the featurebranch.
