### ISSUE TITLE
Add content programatically?

### ISSUE THREAD

**Issue by AndersBrohus** [PerplexDigital/Perplex.ContentBlocks#48]
Hi :)

Is it possible to add content programatically?
Currently have an old website with alot of older nodes which has to be imported and if possible setup using one block of the blocks that are available :)

**Comment by PerplexDaniel** [comment]
Technically, sure. There are no APIs in our package to create blocks, but you can use Umbraco's `IContentService` and use `SetValue()` to set a ContentBlocks property value yourself. The structure is something like this. Main thing is generating that "Nested Content data" part of the JSON somehow. 

```js

{
  "version": 2,
  "header": {
    "id": "...",
    "definitionId": "...",
    "layoutId": "...",
    "presetId": null,
    "isDisabled": false,
    "content": [{ /* Nested Content data */ }]
  },
  
  "blocks": [
    /* Same format as header */
  ]
}

```

**Comment by AndersBrohus** [comment]
Arh okay!
I would try that :)

Thanks alot :)

Should we change the issue to just insert this in the "documentation"? :)

**Comment by AndersBrohus** [comment]
Arh okay, thanks alot :)

Will try and see how i can do that :)

Should we change the issue to just insert this in the "documentation"? :)

**Comment by PerplexDaniel** [comment]
Added a section about this [to the readme](https://github.com/PerplexDigital/Perplex.ContentBlocks/#creating-content-blocks-programmatically).
