### ISSUE TITLE
Layout description missing

### ISSUE THREAD

**Issue by jveer** [PerplexDigital/Perplex.ContentBlocks#5]
Hi,

Currently the description of a layout is not displayed when selecting the layout for a content block.

**Steps to reproduce:**
- 'Add content'
- 'Pick layout'

**Expected result**
I expect the description of a layout to be displayed so I can inform the client with a bit more information of the layout.

**Current result**
The only description that's currently displayed is the description of the content block itself, instead of the layout.

I did have a look in the code to create a pull-request, but I noticed the description of the content block itself is outside the loop of the layouts, so this might be intended behavior?

Hope you can have a look at this. Please let me know if you need any more information.

Best,
Jeffrey

**Comment by PerplexDaniel** [comment]
Yeah this is a known issue, it's also mentioned in the documentation that the description is not showing atm. I'm not really sure why our designer did not include the description at all but it's been like this in our projects as well so it was probably intended. I also would prefer to show the description there, makes sense.

However, as you mention the description is indeed not available in the `ng-repeat` at the moment. The HTML has be changed a bit to support this, but should be possible without breaking too much.

I'll try to have a quick look soon-ish (this week or so) but feel free to submit a PR for this ;-)

**Comment by jveer** [comment]
I've created a PR for the issue. I've also removed the block description from the layout picker as it can cause similar descriptions to be displayed and shouldn't provide any information you need as you already picked that block. The description of the layout should be sufficient.

If you don't agree, just let me know and I'll see what I can do for you :)

**Comment by PerplexDaniel** [comment]
@jveer I've merged the PR code to `master`. The fix will be part of `v1.4.0`, to be released this week. A release candidate is available on NuGet now, which will likely be equivalent to `1.4.0` assuming I don't catch any last minute bugs. So this issue will be closed.
