### ISSUE TITLE
After 2.1.2 users must have access to Settings for the editor to work

### ISSUE THREAD

**Issue by torerikk** [PerplexDigital/Perplex.ContentBlocks#59]
For some reason UmbracoApi/DataType/GetById doesn't have the same access settings as GetAll. So when moving from GetAll to GetById it's no longer possible for a user in the "Editors" group to do anything on a page using ContentBlocks.
Using Umbraco 8.18.3

**Comment by PerplexDaniel** [comment]
Hi @torerikk,

Ah that's unfortunate. I can reproduce this issue on Umbraco 8, it actually works fine on Umbraco 9. I will revert the change and push 2.1.4 right away. Using GetAll() is slightly less efficient of course but it's no big deal.

**Comment by PerplexDaniel** [comment]
2.1.4 is released on NuGet, this should fix the issue. If it somehow persists let me know.
