### ISSUE TITLE
Update example code in README for v11

### ISSUE THREAD

**Issue by raymondbrink** [PerplexDigital/Perplex.ContentBlocks#74]
When copy/pasting the example code in the main README.md from this repo into a v11 project, the code doesn't compile. Some minor changes are needed to make it work correctly for v11.

**Comment by PerplexDaniel** [comment]
@raymondbrink Sounds like you already made the adjustments, would it be possible to make a PR to update the README with a version for v11, keeping the existing one as well? I assume it's the same actually for v9/v10/v11 and the existing one is v8 only.

**Comment by PerplexDaniel** [comment]
Fixed by #75
