### ISSUE TITLE
Hide "Pick layout" and layout switcher if there is only one layout available

### ISSUE THREAD

**Issue by glombek** [PerplexDigital/Perplex.ContentBlocks#8]
Would it be possible to hide the "Pick layout" button in the add dialog and the carousel within the block editor if there is only one available layout?

**Comment by PerplexDaniel** [comment]
Duplicate of #3, reopen and discuss there if you want. It's not unreasonable but it's inconsistent if a button/carousel sometimes shows and sometimes does not. If this will be implemented it should be a config option (default off).

**Comment by glombek** [comment]
This issue should not be closed due to inactivity - these will take time to fix but remain severe accessibility issues.
